type=item
items=minecraft:crossbow
model=aa-12

model.crossbow_pulling_0=aa-12

model.crossbow_pulling_1=aa-12

model.crossbow_pulling_2=aa-12

model.crossbow_arrow=aa-12_ads

model.crossbow_firework=aa-12_ads

nbt.CustomModelData=18