type=item
items=minecraft:crossbow
model=ak-47

model.crossbow_pulling_0=ak-47

model.crossbow_pulling_1=ak-47

model.crossbow_pulling_2=ak-47

model.crossbow_arrow=ak-47_ads

model.crossbow_firework=ak-47_ads
nbt.CustomModelData=4