type=item
items=minecraft:crossbow
model=awp
model.crossbow_pulling_0=awp_1
model.crossbow_pulling_1=awp_2
model.crossbow_pulling_2=awp
model.crossbow_arrow=awp_ads
model.crossbow_firework=awp_ads
nbt.CustomModelData=20