type=item
items=minecraft:crossbow
model=barret
model.crossbow_pulling_0=barret
model.crossbow_pulling_1=barret
model.crossbow_pulling_2=barret
model.crossbow_arrow=barret_ads
model.crossbow_firework=barret_ads
nbt.CustomModelData=52