type=item
items=minecraft:crossbow
model=bazooka
model.crossbow_pulling_0=bazooka
model.crossbow_pulling_1=bazooka
model.crossbow_pulling_2=bazooka
model.crossbow_arrow=bazooka_ads
model.crossbow_firework=bazooka_ads
nbt.CustomModelData=0