type=item
items=minecraft:crossbow
model=cheytac

model.crossbow_pulling_0=cheytac_1

model.crossbow_pulling_1=cheytac_2

model.crossbow_pulling_2=cheytac

model.crossbow_arrow=cheytac_ads

model.crossbow_firework=cheytac_ads
nbt.CustomModelData=82