type=item
items=minecraft:crossbow
model=famas

model.crossbow_pulling_0=famas

model.crossbow_pulling_1=famas

model.crossbow_pulling_2=famas

model.crossbow_arrow=famas_ads

model.crossbow_firework=famas_ads
nbt.CustomModelData=64