type=item
items=minecraft:crossbow
model=m4

model.crossbow_pulling_0=m4

model.crossbow_pulling_1=m4

model.crossbow_pulling_2=m4

model.crossbow_arrow=m4_ads

model.crossbow_firework=m4_ads
nbt.CustomModelData=25