type=item
items=minecraft:crossbow
model=m4s90

model.crossbow_pulling_0=m4s90

model.crossbow_pulling_1=m4s90

model.crossbow_pulling_2=m4s90

model.crossbow_arrow=m4s90_ads

model.crossbow_firework=m4s90_ads

nbt.CustomModelData=7