type=item
items=minecraft:crossbow
model=microuzi

model.crossbow_pulling_0=microuzi

model.crossbow_pulling_1=microuzi_load

model.crossbow_pulling_2=microuzi

model.crossbow_arrow=microuzi_ads

model.crossbow_firework=microuzi_ads

nbt.CustomModelData=49