type=item
items=minecraft:crossbow
model=mp5

model.crossbow_pulling_0=mp5

model.crossbow_pulling_1=mp5_load

model.crossbow_pulling_2=mp5

model.crossbow_arrow=mp5_ads

model.crossbow_firework=mp5_ads

nbt.CustomModelData=3