type=item
items=minecraft:crossbow
model=sawed-off

model.crossbow_pulling_0=sawed-off_1

model.crossbow_pulling_1=sawed-off_2

model.crossbow_pulling_2=sawed-off

model.crossbow_arrow=sawed-off_ads

model.crossbow_firework=sawed-off_ads
nbt.CustomModelData=63